tags:
  Vue: "#4fc08d"
  Hexo: "#0E834D"
  CSS: "#5298d1"
  Node.js: "#026E00"
  Git: "#F14E32"
  React: "#61dafb"
  Python: "#3776ab"
  PHP: "#8892BF"
  VS Code: "#0066B8"
  JavaScript: "#F4DF4F"
  Java: "#4d3900"
  TypeScript: "#317AC6"
  Laravel: "#F4645F"

google_analytics:
  enable: false
  id: G-1M27JF37R1

head:
  js:
    async:
      data-website-id="db1b587e-7774-4012-842d-5d01553dc40b" https://umami.chitang.tech/umami.js


preload:
  style:
    - /css/hexo-theme-yun.css
  script:
    - /js/utils.js
    - /js/hexo-theme-yun.js

prefetch:
  script:
    - /js/sidebar.js

dns_prefetch:
  - https://cos.yunyoujun.cn

# do more(TCP handshake...) than dns-fetch
preconnect:
  - https://fastly.jsdelivr.net

social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: GitHub
    link: https://github.com/chitang233
    icon: icon-github-line
    color: "#181717"
  - name: E-Mail
    link: mailto:chitang233@proton.me
    icon: icon-mail-line
    color: "#8E71C1"
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=474383058
    icon: icon-netease-cloud-music-line
    color: "#C10D0C"
  - name: 知乎
    link: https://www.zhihu.com/people/chi-tang-jun-23
    icon: icon-zhihu-line
    color: "#0084FF"
  - name: bilibili
    link: https://space.bilibili.com/113980518
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: Telegram
    link: https://t.me/chitang233
    icon: icon-telegram-line
    color: "#0088CC"
  - name: Telegram Group
    link: https://t.me/chitang_group
    icon: icon-telegram-fill
    color: "#0088CC"
  - name: QQ
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: https://wpa.qq.com/msgrd?v=3&uin=1194927439&site=qq&menu=yes
    icon: icon-qq-line
    color: "#12B7F5"
#  - name: Discord Channel
#    link: https://discord.gg/SrJVKFj5XC
#    icon: icon-discord-fill
#    color: "#7289DA"
#  - name: Travelling
#    link: https://travellings.link
#    icon: icon-send-plane-2-line
#    color: black

banner:
  enable: true
  title: 池塘的博客
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

notice:
  enable: false

mode: auto

bg_image:
  enable: false
  url: biat
  # dark:
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8

engine_search:
  enable: true
  href: "https://www.google.com/search?q=site:"
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: chitang.tech

search:
  modal: true
  bg_image: https://fastly.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg
  # dark_bg_image: xxx
  # placeholder:

trianglify:
  enable: true
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .post-content img

cursor:
  enable: false
  default: https://fastly.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://fastly.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://fastly.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur

sidebar:
  bg_image: https://fastly.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

avatar:
  enable: true
  url: images/avatar.webp
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: 🖕
    message: 字节我操你妈

font:
  cdn:
    enable: false


menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    # - type: categories
    #   path: /categories/
    #   icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: icon-cloud-line
    #   count: 你猜
  # custom:
  #   title: Github
  #   path: https://github.com/chitang233
  #   icon: icon-github-line

pages:
  - name: 友链
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue

post_card:
  opacity: 0.8

types:
  link:
    color: blue
    icon: icon-external-link-line
  bilibili:
    color: "#FF8EB3"
    icon: icon-bilibili-line
  github:
    color: black
    icon: icon-github-line
  netease-cloud-music:
    color: "#C10D0C"
    icon: icon-netease-cloud-music-line
  notion:
    color: black
    icon: icon-notion
  twitter:
    color: "#1da1f2"
    icon: icon-twitter-line
  weibo:
    color: "#E6162D"
    icon: icon-weibo-line
  zhihu:
    color: "#0084FF"
    icon: icon-zhihu-line

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

post_edit:
  enable: false
  url: https://github.com/chitang233/chitang233.github.io/tree/source/

codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

creative_commons:
  license: by-sa
  post: true
  language: deed.zh
  clipboard: false

lazyload:
  enable: true

reward:
  enable: true
  icon: icon-hand-coin-line
  comment: 给点饭钱
  methods:
     - name: 爱发电
       path: /images/QRCodes/afdian.png
       color: "#7b5bc3"
       icon: /icon/afdian.png
     - name: TRON-TRX20
       path: /images/QRCodes/trx.png
       color: "#b73e31"
       icon: /icon/tron.png
#    - name: 支付宝
#      path: /images/QRCodes/alipay.png
#      color: "#00A3EE"
#      icon: icon-alipay-line
#    - name: QQ 支付
#      path: /images/QRCodes/qq.png
#      color: "#12B7F5"
#      icon: icon-qq-line
#    - name: 微信支付
#      path: /images/QRCodes/wechat.png
#      color: "#2DC100"
#      icon: icon-wechat-pay-line

footer:
  since: 2020
  icon:
    name: icon-cloud-line
    animated: true
    color: "#0078E7"
  powered:
    enable: true
  live_time:
    enable: true
    prefix: 本博客已运行
    suffix: (●'◡'●)
    start_time: "2020-06-25T20:49:30"

say:
  enable: true
  api: https://fastly.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  src: /js/say.js
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

mourn:
  enable: true
  days:
    - "4-4"
    - "12-13"

girls:
  enable: false

comment:
  enable: true

github_issues:
  enable: false
  username: chitang233
  repository: chitang233.github.io
  filters: is:issue

utterances:
  enable: true
  repo: chitang233/chitang233
  issue-term: pathname
  label: comment
  theme: github-light

# search
# https://github.com/wzpan/hexo-generator-search
local_search:
  enable: true
  src: /js/search/local-search.js

busuanzi:
  enable: false
  site_uv: false
  site_uv_icon: icon-user-line
  site_pv: false
  site_pv_icon: icon-eye-line
  page_pv: false
  page_pv_icon: icon-eye-line

wordcount:
  enable: true
  count: true
  time: true

wordcloud:
  enable: true
